name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Run Docker Container
        run: |
          docker build -t fastapi-app .
          docker run -d -p 8000:8000 fastapi-app
